// Equity curve data — language-independent, 2021-05 to 2026-05 (62 points, base=100)
// `cl` key holds the STRATEGY series: TQQQ+GLD+TLT equal-weight hedged combine (SMA200+ATR
//   trigger), daily equity from `alpha-forge backtest combine`, normalized to 100 at period start,
//   sampled at month-ends. SPY/QQQ: Buy & Hold price return, same period & normalization.
//   Endpoints equal the daily total returns (strat +113%, qqq +120%, spy +91%).
window.EQUITY_CURVE = {
  cl:  [100.0,95.8,105.9,108.4,110.5,104.6,110.1,111.8,112.3,105.4,102.8,104.2,96.7,95.3,92.3,95.2,93.0,89.7,89.7,91.4,89.6,92.1,91.2,99.1,99.2,111.1,115.6,118.8,116.4,104.6,104.1,117.4,129.2,130.3,135.2,136.7,128.5,137.1,150.7,148.6,149.0,147.2,143.4,149.5,150.5,152.7,140.8,134.1,133.6,139.5,153.6,159.5,157.6,165.3,171.9,169.9,165.2,169.4,169.0,161.0,191.5,213.4],
  spy: [100.0,100.4,102.7,105.2,108.3,103.3,110.5,109.6,114.7,108.7,105.5,109.4,99.8,100.0,91.8,100.2,96.2,87.3,94.4,99.6,93.9,99.8,97.3,100.9,102.5,102.9,109.6,113.2,111.4,106.1,103.8,113.3,118.4,120.3,126.6,130.7,125.5,131.8,136.5,138.1,141.3,144.3,143.0,151.6,147.9,151.9,149.9,141.6,140.4,149.2,156.9,160.5,163.8,169.6,173.6,174.0,174.1,176.7,175.2,166.5,184.0,190.9],
  qqq: [100.0,99.3,105.5,108.6,113.1,106.7,115.1,117.4,118.8,108.4,103.5,108.4,93.6,92.1,83.9,94.5,89.6,80.2,83.4,88.0,80.1,88.6,88.3,96.7,97.1,104.8,111.4,115.7,114.0,108.2,106.0,117.4,124.0,126.3,132.9,134.6,128.7,136.6,145.5,143.0,144.6,148.4,147.1,155.0,155.7,159.1,154.8,143.0,145.0,158.3,168.5,172.5,174.2,183.6,192.3,189.3,188.1,190.4,185.9,176.9,204.7,219.9],
  // x-axis: indices into the 62-point arrays where each year label sits
  // index 0 = period start (2021-05), 9 = Jan 2022, 21 = Jan 2023, 33 = Jan 2024, 45 = Jan 2025, 57 = Jan 2026
  yearLabels: ['2021','2022','2023','2024','2025','2026'],
  yearIndices: [0, 9, 21, 33, 45, 57],
};

// Bilingual copy — window.COPY
window.COPY = {
  ja: {
    nav: { products: 'プロダクト', pricing: '料金', install: 'インストール', tutorial: 'チュートリアル', faq: 'FAQ', docs: 'ドキュメント', follow: 'フォロー' },
    hero: {
      tag: 'ベータ提供中',
      h1a: 'エージェントに、',
      h1b: '戦略開発を任せる。',
      desc: 'Claude Code に「戦略を探して」と頼むだけ。AI エージェントがバックテスト・Optuna ベイズ最適化・ウォークフォワード検証・Pine Script v6 出力までを自律実行する、エージェントネイティブなクオンツ CLI。先物・株式・FX に対応。',
      cta1: '無料で試す',
      cta2: 'AI エージェントと使う',
    },
    trialStart: {
      label: 'Trial で開始',
      title: 'Whop 登録なしですぐ試す',
      subtitle: 'Trial プランは Whop 登録不要・期限なし。インストール後すぐにバックテスト・ウォークフォワード分析・ベイズ最適化をローカル環境で試せます。データは 2023/12/31 まで・最適化 50 回・Pine Script 生成なしの制限あり。Lifetime プランで全機能が解放されます。',
      primaryCta: '2 ステップで始める',
      secondaryCta: '料金比較を見る',
      updateCta: '更新情報をXで追う',
      availability: '有料プラン（Lifetime / Annual / Monthly）は現在購入可能です。Trial プランはインストール直後から無料で試せます。',
      outExamplesCta: '出力サンプルを見る',
      steps: [
        { num: '01', title: 'CLI をインストール', desc: 'macOS / Linux / Windows 向けの CLI を 1 コマンドで導入します。Whop 登録は不要です。' },
        { num: '02', title: 'サンプル戦略を実行 & 結果確認', desc: 'インストール直後から forge コマンドが Trial プランで動作。用意された戦略 JSON でバックテストを実行し、指標・損益曲線・最適化結果を確認します。' },
      ],
      limits: [
        'データは2023年12月31日まで',
        '最適化50回',
        'Pine Script生成なし',
      ],
    },
    heroStats: [
      { val: 'MCP + スキル 8 種', accent: false, lbl: 'コマンド 5 + スキル 3・Claude Code / Codex 対応' },
      { val: '無人 24/7', accent: true, lbl: '指標 × 銘柄を夜間に自律探索（探索→最適化→検証）' },
      { val: 'Trial 無料', accent: false, lbl: 'Whop 登録不要・期限なしで今すぐ試せる' },
    ],
    aiAgents: {
      label: 'AI エージェント連携',
      title: '「探して」と頼めば、\n検証済みの候補が返ってくる',
      subtitle: 'AlphaForge は AI コーディングエージェントからの利用を前提に設計しています。同梱スキル・MCP サーバ・非対話 CLI の 3 つの接続経路を備え、戦略の探索からウォークフォワード検証・Pine Script 出力まで、エージェントに任せられます。',
      chat: {
        title: 'Claude Code — AlphaForge セッション',
        lines: [
          { role: 'user',  text: 'SPY で未試行の指標の組み合わせを探索して、ウォークフォワード検証に合格した戦略だけ残して' },
          { role: 'agent', text: '/explore-strategies を起動して自律探索を開始します。' },
          { role: 'tool',  text: 'alpha-forge backtest run SPY --strategy my_rsi_v1 --json' },
          { role: 'tool',  text: 'alpha-forge optimize run SPY --strategy my_rsi_v1 --trials 50 --json' },
          { role: 'tool',  text: 'alpha-forge optimize walk-forward SPY --strategy my_rsi_v1_optimized --json' },
          { role: 'agent', text: '✓ OOS 5 窓すべて正リターン。戦略 JSON と Pine Script v6 を保存しました。' },
        ],
      },
      paths: [
        {
          name: 'エージェントスキル',
          badge: '同梱',
          desc: 'alpha-forge system init が /explore-strategies など 5 つのスラッシュコマンドと 3 つのスキルを作業ディレクトリに展開。夜間の自律探索ループも Claude Code / Codex からすぐ回せます。',
          code: 'alpha-forge system init',
          tags: ['Claude Code', 'Codex', '/explore-strategies'],
        },
        {
          name: 'MCP サーバ',
          badge: 'Alpha',
          desc: 'uvx alpha-forge-mcp で起動する OSS（Apache-2.0）の MCP サーバ。戦略一覧・バックテスト・最適化・Pine Script 生成を 7 つのツールとして公開します。',
          code: 'claude mcp add --scope user alpha-forge -- uvx alpha-forge-mcp',
          tags: ['Claude Code', 'Claude Desktop', 'Cursor'],
        },
        {
          name: 'エージェントフレンドリー CLI',
          badge: '標準',
          desc: '全コマンド --json 対応・FORGE_NONINTERACTIVE=1 で確認プロンプトを排除・終了コード規約（0/1/2）。どんなエージェントからも、CLI を直接呼ぶだけで安全に連携できます。',
          code: 'FORGE_NONINTERACTIVE=1 alpha-forge backtest run SPY --json',
          tags: ['--json', 'exit 0/1/2', '非対話モード'],
        },
      ],
      ecosystem: 'さらに alpha-visualizer の REST API でバックテスト結果を読み取り、alpha-strike の status API で運用状態を監視 — エコシステム全体がエージェントから操作できます。',
      docsCta: 'AI エージェント連携ガイドを読む',
    },
    availability: {
      label: '現在のステータス',
      title: '今すぐ使えるもの・\nこれから提供するもの',
      subtitle: '購入や利用の前に、いま使える範囲と今後の予定をひと目で確認できます。下のプラン・ロードマップの記載と一致しています。',
      columns: [
        {
          tone: 'now',
          status: '今すぐ使える',
          mark: '✓',
          title: '本日から利用可能',
          items: [
            'Trial プラン（無料・Whop 登録不要・期限なし）',
            '有料プラン（Lifetime / Annual / Monthly）を購入可能',
            'alpha-visualizer（OSS・PyPI 公開）',
            'バックテスト・ベイズ最適化・ウォークフォワード検証・Pine Script v6 生成',
          ],
        },
        {
          tone: 'beta',
          status: 'ベータ提供中',
          mark: '◐',
          title: '利用可能・改善継続中',
          items: [
            'alpha-forge コア（Beta 版・購入して利用可能、v1.0 へ向け改善中）',
            'alpha-strike 自動執行サーバー（早期開発 / Dev）',
            'AI エージェント連携 — 同梱スキル（/explore-strategies など）+ MCP サーバ（uvx alpha-forge-mcp・alpha 版）',
            'FRED / ALFRED マクロデータ provider（alpha-forge data alt fetch FRED: / backtest --regime-filter macro:）',
          ],
        },
        {
          tone: 'planned',
          status: '正式版で予定',
          mark: '○',
          title: '2026 年夏予定',
          items: [
            'v1.0 正式リリース（全プロダクト）',
            'MCP サーバ正式版（alpha 版は uvx alpha-forge-mcp で公開中）',
            'サポート・コミュニティ体制の整備',
          ],
        },
      ],
    },
    pricing: {
      label: '料金',
      title: '使い方に合わせて\n選べるプラン',
      subtitle: 'Trial プラン（Whop 登録不要・期限なし）で無料お試し。フル機能解放は Lifetime（買い切り）/ Annual / Monthly のいずれかから選べます。ローンチ記念: 先着 50 名は Lifetime を $299 で販売（通常 $799）。Annual / Monthly は通常価格で提供します。',
      trialPlan: {
        title: 'Trial プランで始める',
        badge: 'Trial',
        desc: 'Whop 登録なし・インストール直後から利用可能。バックテスト・ベイズ最適化・ウォークフォワード分析を無料で試せます。\n2023年12月31日までのデータ・最適化50回上限・Pine Script 生成なし。',
        pills: [
          { label: '✓ バックテスト',       type: 'ok' },
          { label: '✓ ウォークフォワード', type: 'ok' },
          { label: '最適化 50回上限',      type: 'limit' },
          { label: 'データ 〜2023/12/31',   type: 'limit' },
          { label: 'Pine Script 生成',     type: 'no' },
        ],
        ctaLabel: 'インストール手順を見る',
        ctaHint: 'Whop 登録は不要です',
        comingSummer: 'Trial は本日から利用可能',
        url: '/ja/install.html',
      },
      plans: [
        {
          name: 'Lifetime（Early Bird）',
          badge: 'ローンチ記念・先着50名',
          featured: true,
          price: '$299',
          period: '買い切り',
          desc: '先着50名様への早割価格。通常 $799 が $299。早割の $299 クーポンは X（@alforge_bot）をフォローのうえ DM で配布します。常に最新バージョンを利用可能。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            '常に最新バージョンを利用可能（v2 以降のメジャーアップグレードも追加料金なし）',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Annual',
          badge: null,
          featured: false,
          price: '$159',
          period: '/ 年',
          desc: '年間サブスクリプション。Monthly比 約30% お得。常に最新バージョンを利用できます。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            '常に最新バージョン',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Monthly',
          badge: null,
          featured: false,
          price: '$19',
          period: '/ 月',
          desc: '月額サブスクリプション。必要な期間だけ最新バージョンを利用できます。',
          features: [
            'macOS / Linux / Windows 対応',
            'シミュレーション（回数無制限）',
            'ベイズ最適化（Optuna）',
            'ウォークフォワード分析',
            'Pine Script v6 自動生成',
            '常に最新バージョン',
            '個人利用の範囲で複数端末対応',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
      ],
      buyNow: '今すぐ購入',
      note: 'ローンチ記念の早割 Lifetime $299 は先着50名限定。早割の $299 クーポンは X（@alforge_bot）をフォローのうえ DM で配布します。早割枠が埋まると Lifetime は通常価格 $799 になります（合計100席上限）。Lifetime は常に最新バージョンを利用可能で、v2 以降のメジャーアップグレードも追加料金はかかりません。Annual / Monthly は通常価格のサブスクリプションで、常に最新バージョンを利用できます。購入後は alpha-forge system auth login を実行して Whop OAuth 認証で有効化します。',
      comparison: {
        label: 'プラン比較',
        colTrial: 'Trial（Whop 登録不要）',
        colLifetime: '有料プラン（Lifetime / Annual / Monthly）',
        rows: [
          { feature: 'macOS / Linux / Windows 対応',    trial: 'ok',    lifetime: 'ok' },
          { feature: 'バックテスト（シミュレーション）', trial: 'limit', trialNote: '2023/12/31までのデータのみ', lifetime: 'ok', lifetimeNote: '✓ 最新データ含む' },
          { feature: 'ウォークフォワード分析',           trial: 'limit', trialNote: '2023/12/31までのデータのみ', lifetime: 'ok', lifetimeNote: '✓ 最新データ含む' },
          { feature: 'ベイズ最適化（Optuna）',           trial: 'limit', trialNote: '最大 50 回 / 実行',   lifetime: 'ok', lifetimeNote: '✓ 回数無制限' },
          { feature: '最新ヒストリカルデータ取得',        trial: 'no',    lifetime: 'ok' },
          { feature: 'Pine Script v6 自動生成',          trial: 'no',    lifetime: 'ok' },
          { feature: 'メジャーバージョンアップデート',    trial: 'ok',    lifetime: 'ok', lifetimeNote: '✓ 常に最新バージョン' },
          { feature: '複数端末での利用',                  trial: 'ok',    lifetime: 'ok', lifetimeNote: '✓ 個人利用の範囲で複数端末' },
        ],
      },
    },
    products: {
      label: 'プロダクト',
      title: '3つの層で構成される\n統合データ処理システム',
      subtitle: 'forge で戦略を半自動開発・最適化、visualizer で可視化・分析からパラメータチューニングまで、strike が外部 Webhook をトリガーに自動執行。3 層すべてが --json CLI / REST API を備え、AI エージェントから操作できる戦略開発ループ。',
      items: [
        {
          id: 'forge',
          badge: 'Beta',
          badgeType: 'beta',
          icon: '⚙',
          name: 'forge',
          role: 'シミュレーション・最適化エンジン',
          desc: '投資戦略定義をvectorbtで高速シミュレーション。Optunaによるベイズ最適化・ウォークフォワード検証で過学習を防ぎ、Pine Script v6を自動生成。戦略・最適化結果・ジャーナルは JSON / SQLite で一元管理。同梱スキル + MCP サーバで AI エージェントが自律探索。',
          tags: ['Python', 'vectorbt', 'Optuna', 'SQLite', 'Pine Script'],
          accent: 'var(--blue)',
          links: [
            { label: 'ドキュメント', href: 'docs/' },
            { label: 'インストール', href: 'install.html' },
          ],
        },
        {
          id: 'visualizer',
          badge: 'OSS',
          badgeType: 'released',
          icon: '▦',
          name: 'visualizer',
          role: '可視化・分析・チューニング GUI',
          desc: 'forge のバックテスト・最適化結果を可視化し、ブラウザから実行まで行える OSS ダッシュボード。Equity / Drawdown / WFO 合成カーブ、複数戦略の Pearson 相関、ライブ実績との diff に加え、バックテスト・最適化・WFT の GUI 実行とパラメータチューニングループ（編集→一時実行→比較→明示保存）に対応。REST API でエージェントからも結果を読み取り可能。閲覧は forge 本体非依存で動作。',
          tags: ['Python', 'React', 'SQLite', 'PyPI', 'Apache-2.0'],
          accent: 'var(--accent)',
          links: [
            { label: 'ドキュメント', href: 'docs/alpha-visualizer/' },
            { label: 'GitHub', href: 'https://github.com/alforge-labs/alpha-visualizer', external: true },
            { label: 'PyPI', href: 'https://pypi.org/project/alpha-visualizer/', external: true },
          ],
        },
        {
          id: 'strike',
          badge: 'Dev',
          badgeType: 'dev',
          icon: '⚡',
          name: 'strike',
          role: 'Webhook・自動実行サーバー',
          desc: '外部 Webhook シグナルを FastAPI で受け取り、外部 API へ自動リクエスト送信。実行・レスポンスイベントをJSONLで記録。Dockerデプロイ対応。',
          tags: ['FastAPI', 'OANDA', 'moomoo', 'Docker', 'Webhook'],
          accent: 'var(--amber)',
          links: [
            { label: 'セットアップガイド', href: 'docs/guides/alpha-strike-setup/' },
            { label: 'GitHub', href: 'https://github.com/alforge-labs/alpha-strike', external: true },
            { label: 'PyPI', href: 'https://pypi.org/project/alpha-strike/', external: true },
          ],
        },
      ],
    },
    perf: {
      label: 'シミュレーション実績',
      title: 'シミュレーション結果（実データ）',
      strategy: 'TQQQ・GLD・TLT 等加重ヘッジ型コンバイン（SMA200+ATR トリガー）— 5年シミュレーション',
      period: '2021.05 – 2026.05（5年）',
      note: '※ 実バックテスト結果（スリッページ 0.05% 込み・price return）。3 倍レバレッジ NASDAQ100（TQQQ）に SMA200+ATR でヘッジを掛け、GLD・TLT を等加重した複合戦略。CAGR は QQQ B&H（16.9%）にわずかに及びませんが SPY B&H（13.7%）を上回り、最大ドローダウンを大幅に圧縮（-23.3% vs QQQ -35.1%）、Sharpe も両ベンチマークを上回ります。本戦略はウォークフォワード検証（WFT）で 2010–2026 の OOS 5 窓すべて正リターンを確認した過学習耐性設計です。過去の結果は将来の成果を保証しません。',
      stats: [
        { val: '+16.2%', label: 'CAGR',          cls: 'val-pos' },
        { val: '0.91',   label: 'Sharpe Ratio',   cls: 'val-neu' },
        { val: '-23.3%', label: 'Max Drawdown',   cls: 'val-neg' },
        { val: '0.69',   label: 'Calmar Ratio',   cls: 'val-neu' },
        { val: '+113%',  label: '累計リターン',   cls: 'val-pos' },
      ],
      legend: [
        { color: 'var(--accent)',  label: '本シミュレーション（TQQQ+GLD+TLT ヘッジ）' },
        { color: 'var(--blue)',    label: 'SPY B&H' },
        { color: 'var(--amber)',   label: 'QQQ B&H' },
      ],
      bench: {
        label: 'vs ベンチマーク（同期間）',
        headers: ['', 'SPY B&H', 'QQQ B&H', '本シミュレーション'],
        rows: [
          { metric: 'CAGR',    spy: '13.7%', qqq: '16.9%', strat: '16.2%', stratWin: false },
          { metric: 'Sharpe',  spy: '0.84',  qqq: '0.81',  strat: '0.91',  stratWin: true },
          { metric: 'Max DD',  spy: '-24.5%',qqq: '-35.1%', strat: '-23.3%',stratWin: true },
        ],
      },
    },
    roadmap: {
      label: 'ロードマップ',
      title: '開発の軌跡と\nこれからの計画',
      items: [
        {
          period: '2026年3月上旬',
          status: 'done',
          badgeLabel: '完了',
          title: 'シミュレーションエンジン構築',
          items: ['シミュレーションエンジン設計・実装', 'データ取得・投資戦略スキーマ・CLI 構築', '最適化パイプライン・Pine Script 生成'],
        },
        {
          period: '2026年3月中旬〜下旬',
          status: 'done',
          badgeLabel: '完了',
          title: '分析機能拡充',
          items: ['HMM インジケータ・ウォークフォワード分析', 'バックテスト履歴 DB・チャート生成', 'リスク管理拡張（動的 SL/TP）'],
        },
        {
          period: '2026年3月末',
          status: 'done',
          badgeLabel: '完了',
          title: 'ライブ実行統合',
          items: ['alpha-strike Webhook サーバー構築', 'OANDA・moomoo API 自動実行対応', '実行・レスポンスイベント分析パイプライン'],
        },
        {
          period: '2026年4月',
          status: 'done',
          badgeLabel: '完了',
          title: 'プロダクト化・製品化',
          items: ['ライセンス管理・バイナリ配布・CI/CD パイプライン', '公式サイト公開', 'Claude 連携自律探索'],
        },
        {
          period: '2026年5月',
          status: 'done',
          badgeLabel: '完了',
          title: 'ベータ版公開',
          items: ['alpha-forge v0.4.0 リリース（macOS / Windows / Linux バイナリ）', 'alpha-visualizer v0.2.0 公開（OSS・TradingView Lightweight Charts）', 'Trial プラン公開', 'ドキュメント整備'],
        },
        {
          period: '2026年夏',
          status: 'active',
          badgeLabel: '進行中',
          title: '正式リリース・商用化',
          items: ['全プロダクト正式リリース（v1.0）', '✅ MCP サーバ PyPI 公開済み（uvx alpha-forge-mcp・Claude Code / Codex / Cursor）', '✅ FRED/ALFRED マクロデータ provider 出荷済み（alpha-forge data alt fetch FRED: / backtest --regime-filter macro:）', 'サポート・コミュニティ体制整備'],
        },
      ],
    },
    faq: {
      label: 'FAQ',
      title: 'よくある質問',
      items: [
        { q: '動作環境は？', a: 'macOS（Apple Silicon / Intel）、Windows 10 以降、Linux に対応した単一バイナリで配布しています。Python やランタイムを別途インストールする必要はなく、ダウンロード後すぐに動作します。' },
        { q: '無料で試せますか？', a: 'Trial プランは Whop 登録不要・期限なしで、インストール直後から利用できます。データは 2023/12/31 まで、最適化は累計 50 回まで、Pine Script 生成は無効、の 3 つの制限があります。フル機能の解放は Lifetime / Annual / Monthly のいずれかを購入後です。' },
        { q: '対応するデータソースは？', a: 'yfinance（株式・ETF）、moomoo（株式・板情報）、OANDA（FX・CFD）、Dukascopy（FX 長期ヒストリカル）の 4 プロバイダーに対応しています。取得したデータはローカルに Parquet キャッシュとして保存されます。' },
        { q: '過学習（オーバーフィット）対策はどうしていますか？', a: 'Optuna TPE によるベイズ最適化とウォークフォワード分析（WFT）を標準搭載しています。`alpha-forge optimize run --split` で IS（学習期間）/ OOS（検証期間）のスコア差を一発で計測でき、過剰最適化の検出に使えます。' },
        { q: 'TradingView は必須ですか？', a: 'alpha-forge 単体での戦略開発・バックテスト・最適化・Pine Script 生成には TradingView は不要です。生成した Pine Script v6 を TradingView でアラート・自動売買に流したい場合や、alpha-strike による自動執行を組む場合のみ TradingView アカウントが必要になります。' },
        { q: 'AI エージェントと組み合わせて使えますか？', a: 'はい、それが AlphaForge の中核ユースケースです。Claude Code / Codex 用のスキル（/explore-strategies など 5 コマンド + 3 スキル）を同梱するほか、MCP サーバ（uvx alpha-forge-mcp・alpha 版）経由で Claude Code / Claude Desktop / Cursor からも操作できます。CLI 自体も全コマンド --json 出力・非対話モード（FORGE_NONINTERACTIVE=1）・終了コード規約を備え、夜間の自律探索ループを安全に無人実行できます。' },
        { q: '複数 PC で使えますか？／アップデートは？', a: 'Trial・有料プランとも、個人利用の範囲で複数端末に対応します（honor system、詳細は EULA を参照）。Lifetime は常に最新バージョンを利用でき、v2 以降のメジャーアップグレードも追加料金はかかりません。' },
      ],
    },
    systemFlow: {
      label: 'システム全体像',
      title: '探索から実行、実績データの蓄積までを一気通貫でつなぐ',
      subtitle: 'AlphaForgeで戦略を検証・最適化し、AlphaStrategiesに成果物を集約。TradingViewのアラートをAlphaStrikeが受け取り、Broker APIへ注文を送ります。約定・ポジション・損益データはLive Dataとして戻り、バックテスト結果とあわせてAlphaVisualizerで可視化し、次の分析に活用します。',
      alt: 'AlphaTradeのシステムフロー図',
    },
    usecases: {
      label: '活用シーン',
      title: 'あらゆる市場・戦略スタイルに\n対応する定量フレームワーク',
      subtitle: 'AlphaForge の統計エンジンで、先物・株式・FX を問わず定量的な投資戦略の開発・検証・最適化サイクルをカバーします。',
      items: [
        {
          icon: '🛢️',
          accent: 'var(--amber)',
          label: 'Futures & Commodities',
          title: '先物・商品取引戦略',
          desc: 'WTI原油（CL=F）や金（GC=F）など商品先物市場に HMM 状態遷移モデルを適用。市場レジームの変化を自動検出し、ドローダウンを抑制しながら安定したリターンを追求します。',
          tags: ['先物取引', 'HMM', 'レジーム検出', 'CL=F / GC=F'],
        },
        {
          icon: '📈',
          accent: 'var(--blue)',
          label: 'Equity Index',
          title: '株式インデックス戦略',
          desc: 'S&P500（SPY）や NASDAQ100（QQQ）に MACD・RSI を組み合わせた複合戦略を構築。ウォークフォワード分析でロバストな長期パフォーマンスを厳密に検証します。',
          tags: ['株式インデックス', 'MACD / RSI', 'ウォークフォワード', 'SPY / QQQ'],
        },
        {
          icon: '💱',
          accent: 'var(--accent)',
          label: 'FX / Forex',
          title: '外国為替戦略',
          desc: 'USDJPY・EURUSD など主要通貨ペアへのベイズ最適化による高次元パラメータ探索。Grid Search より効率的に最適解を発見し、過剰最適化（曲線あてはめ）を防止します。',
          tags: ['FX 戦略', 'ベイズ最適化', '通貨ペア', 'USDJPY / EURUSD'],
        },
      ],
    },
    personaUseCases: {
      label: '誰向け？',
      title: 'あなたの目的から始める',
      subtitle: 'バックグラウンドや目的に合わせた入口を選んでください。',
      personas: [
        {
          icon: '✨',
          label: 'AI Agent Users',
          title: 'AIエージェント利用者',
          desc: '同梱スキル + MCP サーバ + 非対話 CLI。Claude Code などのエージェントに、戦略の探索から検証・Pine Script 生成まで任せる非同期ワークフロー。',
          link: '/ja/docs/usecases/ai-agents/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '📊',
          label: 'TradingView Users',
          title: 'TradingViewユーザー',
          desc: 'Pine Scriptでアイデアを試作し、AlphaForgeでバックテスト・最適化を本格化。Pine Script再エクスポートまで一気通貫。',
          link: '/ja/docs/usecases/tradingview/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🐍',
          label: 'Python Developers',
          title: 'Python開発者',
          desc: 'JSON宣言型の戦略管理、CLIの構造化出力、Optunaベースの最適化。Pythonエコシステムとシームレスに連携。',
          link: '/ja/docs/usecases/python-dev/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🔬',
          label: 'Quants & Researchers',
          title: 'クオンツ・研究者',
          desc: 'ウォークフォワード検証・ベイズ最適化・再現性保証。統計的な厳密性を求める研究者向けの定量評価環境。',
          link: '/ja/docs/usecases/quants/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '🤖',
          label: 'Automated Trading',
          title: '自動売買検討者',
          desc: 'バックテスト→最適化→Pine Script生成→TradingViewアラート→Alpha Strike自動発注まで一貫した環境。',
          link: '/ja/docs/usecases/auto-trading/',
          linkLabel: '詳しく見る →',
        },
        {
          icon: '📘',
          label: 'Discretionary → Systematic',
          title: '裁量トレーダーのシステム化',
          desc: '頭の中のトレードルールをJSON宣言型で明示化し、バックテストで感情の偏りを定量検証。再現性のあるシステム取引へ昇華。',
          link: '/ja/docs/usecases/discretionary/',
          linkLabel: '詳しく見る →',
        },
      ],
    },
    longTermValue: {
      label: '継続利用価値',
      title: '戦略は、作って終わりではない',
      subtitle: 'マーケット、研究、実装アイデアは変わり続けます。alpha-forge は一度きりの検証ツールではなく、戦略を見直し続けるための開発ループです。',
      items: [
        {
          eyebrow: 'Regime Shift',
          title: '市場レジームは変わる',
          desc: '一度よい結果を出した投資戦略でも、ボラティリティ・金利・流動性・参加者行動の変化で将来も機能し続けるとは限りません。定期的な再検証が必要です。',
        },
        {
          eyebrow: 'Strategy Intake',
          title: '新しいアイデアは増え続ける',
          desc: 'SSRN などの研究や TradingView の Pine Script コミュニティでは、新しい手法・指標・リスク管理アイデアが継続的に公開されています。検証候補を取り込める状態を保つことが重要です。',
        },
        {
          eyebrow: 'Validation Loop',
          title: '検証ループを回せる',
          desc: 'alpha-forge はバックテスト、ベイズ最適化、ウォークフォワード検証、Pine Script 生成を同じ流れで扱えます。発見した仮説を、再現可能な検証サイクルへ落とし込めます。',
        },
      ],
    },
    trustSafety: {
      label: '信頼・安全・制限',
      title: '購入・利用前に確認してほしいこと',
      subtitle: 'AlphaForge はローカル実行を前提にした開発者向けツールです。データの扱い、ライセンス認証、投資リスク、プラン制限をまとめて確認できます。',
      docsHref: '/ja/docs/legal/trust-safety-limits/',
      docsLabel: '信頼・安全・制限の詳細を読む',
      items: [
        {
          eyebrow: 'Local First',
          title: '戦略データはローカルに残る',
          desc: 'バックテスト設定、API キー・取引履歴・戦略データは通常ローカル環境に留まり、Alforge Labs のサーバーへ送信されません。',
        },
        {
          eyebrow: 'License',
          title: '認証時のみ必要情報を送信',
          desc: 'ライセンス認証時には、ライセンスキー、インスタンス名、アクティベーション日時など、認証に必要な情報だけが外部サービスへ送信されます。',
        },
        {
          eyebrow: 'Risk',
          title: '投資助言ではありません',
          desc: 'AlphaForge は研究・検証用ソフトウェアです。バックテストやシミュレーション結果は将来の成果を保証せず、取引判断はユーザー自身の責任です。',
        },
        {
          eyebrow: 'Plans',
          title: 'Trial / Monthly / Annual / Lifetime',
          desc: 'Trial プラン（Whop 登録不要・無料）はデータ日付と最適化 trial 数の制限あり。Lifetime（買い切り）/ Annual / Monthly のいずれかで最新データ・無制限 trial・Pine Script 出力すべてを解放できます。',
        },
      ],
    },
    follow: {
      label: 'アップデート',
      title: '開発をリアルタイムで追う',
      desc: 'シミュレーション実績レポート・機能アップデート・開発の裏側を定期発信しています。',
      cta: 'X でフォローする',
    },
    disclaimer: {
      title: '⚠️ 重要な免責事項（必ずお読みください）',
      items: [
        { label: 'ソフトウェアの提供', text: '本製品は、時系列データのシミュレーションおよびデータパイプライン自動化を支援する「開発者向けソフトウェアツール」の提供です。特定の運用方法を推奨するものではありません。' },
        { label: 'シミュレーション結果について', text: '本ソフトウェアのシミュレーション結果は過去データに基づくものであり、将来の成果を保証するものではありません。' },
        { label: '利用責任', text: 'パラメータの設定およびシステムトラブルによる影響を含め、本ソフトウェアの利用はすべてユーザー自身の責任の下で行ってください。' },
      ],
    },
    footer: {
      copy: '© 2026 Alforge Labs.',
      note: 'このサイトは開発者向けソフトウェアツールを提供します。特定の投資・運用を推奨するものではありません。',
      links: [
        { label: '利用規約', url: '/terms.html' },
        { label: 'プライバシー', url: '/privacy.html' },
      ],
    },
  },

  en: {
    nav: { products: 'Products', pricing: 'Pricing', install: 'Install', tutorial: 'Tutorial', faq: 'FAQ', docs: 'Docs', follow: 'Follow' },
    hero: {
      tag: 'In Beta',
      h1a: 'Your AI agent',
      h1b: 'runs the quant lab.',
      desc: 'Ask Claude Code to find you a strategy — and your agent autonomously runs backtests, Optuna Bayesian optimization, walk-forward validation, and Pine Script v6 export. An agent-native quant CLI for futures, equities, and FX.',
      cta1: 'Start Free',
      cta2: 'Use with AI Agents',
    },
    trialStart: {
      label: 'Start on Trial',
      title: 'Try it instantly — no Whop registration',
      subtitle: 'The Trial plan requires no Whop registration and never expires. Right after install, backtest, walk-forward analysis, and Bayesian optimization run locally. Limits: data through 2023-12-31, 50 optimization trials, no Pine Script export. The Lifetime plan unlocks everything.',
      primaryCta: 'Start in 2 steps',
      secondaryCta: 'Compare plans',
      updateCta: 'Follow updates on X',
      availability: 'Paid plans (Lifetime / Annual / Monthly) are available to purchase now. The Trial plan is free to try right after install.',
      outExamplesCta: 'See output samples',
      steps: [
        { num: '01', title: 'Install the CLI', desc: 'Install the CLI with a single command on macOS, Linux, or Windows. No Whop registration required.' },
        { num: '02', title: 'Run a sample strategy & review results', desc: 'Right after install, alpha-forge runs on the Trial plan. Backtest a ready-made strategy JSON and inspect metrics, the equity curve, and optimization results.' },
      ],
      limits: [
        'Data through Dec 31, 2023',
        '50 optimization trials',
        'No Pine Script export',
      ],
    },
    heroStats: [
      { val: 'MCP + 8 skills', accent: false, lbl: '5 commands + 3 skills · Claude / Codex' },
      { val: 'Unmanned 24/7', accent: true, lbl: 'Explore → optimize → validate overnight' },
      { val: 'Free Trial', accent: false, lbl: 'No Whop signup, no expiry — start now' },
    ],
    aiAgents: {
      label: 'AI Agent Integration',
      title: 'Ask your agent to explore.\nGet validated candidates back.',
      subtitle: 'AlphaForge is designed for AI coding agents as first-class users. Three integration paths ship out of the box — bundled skills, an MCP server, and a non-interactive CLI — so your agent can handle everything from exploration to walk-forward validation and Pine Script export.',
      chat: {
        title: 'Claude Code — AlphaForge session',
        lines: [
          { role: 'user',  text: 'Explore untried indicator combos on SPY and keep only strategies that pass walk-forward validation' },
          { role: 'agent', text: 'Starting autonomous exploration via /explore-strategies.' },
          { role: 'tool',  text: 'alpha-forge backtest run SPY --strategy my_rsi_v1 --json' },
          { role: 'tool',  text: 'alpha-forge optimize run SPY --strategy my_rsi_v1 --trials 50 --json' },
          { role: 'tool',  text: 'alpha-forge optimize walk-forward SPY --strategy my_rsi_v1_optimized --json' },
          { role: 'agent', text: '✓ All 5 OOS windows positive. Strategy JSON and Pine Script v6 saved.' },
        ],
      },
      paths: [
        {
          name: 'Agent Skills',
          badge: 'Bundled',
          desc: 'alpha-forge system init deploys 5 slash commands (/explore-strategies and more) plus 3 skills into your working directory. Overnight autonomous exploration loops run right from Claude Code or Codex.',
          code: 'alpha-forge system init',
          tags: ['Claude Code', 'Codex', '/explore-strategies'],
        },
        {
          name: 'MCP Server',
          badge: 'Alpha',
          desc: 'An open-source (Apache-2.0) MCP server launched with uvx alpha-forge-mcp. Exposes strategy listing, backtesting, optimization, and Pine Script generation as 7 tools.',
          code: 'claude mcp add --scope user alpha-forge -- uvx alpha-forge-mcp',
          tags: ['Claude Code', 'Claude Desktop', 'Cursor'],
        },
        {
          name: 'Agent-Friendly CLI',
          badge: 'Built-in',
          desc: 'Every command supports --json. FORGE_NONINTERACTIVE=1 removes confirmation prompts, and exit codes follow a strict 0/1/2 contract. Any agent can integrate by calling the CLI directly.',
          code: 'FORGE_NONINTERACTIVE=1 alpha-forge backtest run SPY --json',
          tags: ['--json', 'exit 0/1/2', 'non-interactive'],
        },
      ],
      ecosystem: 'Beyond the core: agents read backtest results through the alpha-visualizer REST API and monitor live execution through the alpha-strike status API — the entire ecosystem is agent-operable.',
      docsCta: 'Read the AI Agent Integration guide',
    },
    availability: {
      label: 'Current Status',
      title: 'What you can use today\nand what is coming next',
      subtitle: 'Before you buy or install, see at a glance what is available now and what is planned. This matches the plans and roadmap below.',
      columns: [
        {
          tone: 'now',
          status: 'Available now',
          mark: '✓',
          title: 'Usable today',
          items: [
            'Trial plan (free · no Whop registration · no expiry)',
            'Paid plans (Lifetime / Annual / Monthly) — purchasable',
            'alpha-visualizer (open source · on PyPI)',
            'Backtest · Bayesian optimization · walk-forward validation · Pine Script v6 export',
          ],
        },
        {
          tone: 'beta',
          status: 'In beta',
          mark: '◐',
          title: 'Usable · actively improving',
          items: [
            'alpha-forge core (Beta — purchasable & usable, evolving toward v1.0)',
            'alpha-strike execution server (early development / Dev)',
            'AI agent integration — bundled skills (/explore-strategies, etc.) + MCP server (uvx alpha-forge-mcp, alpha)',
            'FRED / ALFRED macro data provider (alpha-forge data alt fetch FRED: / backtest --regime-filter macro:)',
          ],
        },
        {
          tone: 'planned',
          status: 'Planned for v1.0',
          mark: '○',
          title: 'Targeting summer 2026',
          items: [
            'v1.0 official release (all products)',
            'MCP server GA (alpha already live: uvx alpha-forge-mcp)',
            'Support & community infrastructure',
          ],
        },
      ],
    },
    pricing: {
      label: 'Pricing',
      title: 'Pick the plan\nthat fits how you use it.',
      subtitle: 'Trial (no Whop registration, no time limit) is permanently free. To unlock everything, pick one of Lifetime (one-time), Annual, or Monthly. Launch promo: the first 50 buyers get Lifetime at $299 (vs the regular $799). Annual and Monthly stay at standard pricing.',
      trialPlan: {
        title: 'Start on Trial',
        badge: 'Trial',
        desc: 'No Whop registration needed. Available immediately after install. Try backtesting, Bayesian optimization, and walk-forward analysis at no cost.\nHistorical data up to Dec 31, 2023 · 50 optimization trials per run · No Pine Script export.',
        pills: [
          { label: '✓ Backtest',           type: 'ok' },
          { label: '✓ Walk-Forward',       type: 'ok' },
          { label: 'Optimization 50 trials max', type: 'limit' },
          { label: 'Data up to Dec 31, 2023', type: 'limit' },
          { label: 'Pine Script export',   type: 'no' },
        ],
        ctaLabel: 'See install steps',
        ctaHint: 'No Whop registration required',
        comingSummer: 'Trial is available today',
        url: '/en/install.html',
      },
      plans: [
        {
          name: 'Lifetime (Early Bird)',
          badge: 'Launch Promo · First 50',
          featured: true,
          price: '$299',
          period: 'one-time',
          desc: 'Early-bird pricing for the first 50 buyers. Regular Lifetime is $799. The $299 early-bird coupon is distributed by DM — follow @alforge_bot on X. Always on the latest version.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'Always on the latest version (major upgrades like v2 at no extra cost)',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Annual',
          badge: null,
          featured: false,
          price: '$159',
          period: '/ year',
          desc: 'Annual subscription. ~30% off vs monthly. Always on the latest version.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'Always the latest version',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
        {
          name: 'Monthly',
          badge: null,
          featured: false,
          price: '$19',
          period: '/ month',
          desc: 'Monthly subscription. Use the latest version for as long as you need it.',
          features: [
            'macOS / Linux / Windows',
            'Unlimited simulations',
            'Bayesian optimization (Optuna)',
            'Walk-forward analysis',
            'Pine Script v6 auto-generation',
            'Always the latest version',
            'Personal use across multiple devices',
          ],
          url: 'https://whop.com/alforge-labs/alphaforge/'
        },
      ],
      buyNow: 'Get Access',
      note: 'Early Bird Lifetime ($299) is limited to the first 50 buyers. The $299 early-bird coupon is distributed by DM — follow @alforge_bot on X. Once the early-bird seats are taken, Lifetime returns to $799 (capped at 100 total seats). Lifetime always runs on the latest version, with no extra fee for major upgrades like v2. Annual and Monthly are standard-priced subscriptions that always run on the latest version. After purchase, run `alpha-forge system auth login` and complete the Whop OAuth flow in your browser to activate.',
      comparison: {
        label: 'Plan Comparison',
        colTrial: 'Trial (no Whop registration)',
        colLifetime: 'Paid Plans (Lifetime / Annual / Monthly)',
        rows: [
          { feature: 'macOS / Linux / Windows',          trial: 'ok',    lifetime: 'ok' },
          { feature: 'Backtest (simulation)',             trial: 'limit', trialNote: 'Historical data up to Dec 31, 2023', lifetime: 'ok', lifetimeNote: '✓ Latest data included' },
          { feature: 'Walk-forward analysis',            trial: 'limit', trialNote: 'Historical data up to Dec 31, 2023', lifetime: 'ok', lifetimeNote: '✓ Latest data included' },
          { feature: 'Bayesian optimization (Optuna)',   trial: 'limit', trialNote: 'Up to 50 trials per run',   lifetime: 'ok', lifetimeNote: '✓ Unlimited' },
          { feature: 'Latest historical data download',  trial: 'no',    lifetime: 'ok' },
          { feature: 'Pine Script v6 auto-generation',   trial: 'no',    lifetime: 'ok' },
          { feature: 'Major version updates',             trial: 'ok',    lifetime: 'ok', lifetimeNote: '✓ Always latest' },
          { feature: 'Multi-device use',                  trial: 'ok',    lifetime: 'ok', lifetimeNote: '✓ Personal use across devices' },
        ],
      },
    },
    products: {
      label: 'Products',
      title: 'Three layers.\nOne integrated system.',
      subtitle: 'alpha-forge develops and optimizes strategies, visualizer takes you from analysis to parameter tuning in the browser, and strike auto-executes on external webhook signals — a complete three-layer loop, with every layer operable by AI agents via --json CLI and REST APIs.',
      items: [
        {
          id: 'forge',
          badge: 'Beta',
          badgeType: 'beta',
          icon: '⚙',
          name: 'forge',
          role: 'Simulation & Optimization Engine',
          desc: 'Simulate investment strategies at high speed with vectorbt. Bayesian optimization via Optuna + walk-forward validation to prevent overfitting. Automatic Pine Script v6 generation. Strategies, optimization results, and journals are managed centrally as JSON/SQLite. Bundled skills + MCP server let AI agents explore autonomously.',
          tags: ['Python', 'vectorbt', 'Optuna', 'SQLite', 'Pine Script'],
          accent: 'var(--blue)',
          links: [
            { label: 'Docs', href: 'docs/' },
            { label: 'Install', href: 'install.html' },
          ],
        },
        {
          id: 'visualizer',
          badge: 'OSS',
          badgeType: 'released',
          icon: '▦',
          name: 'visualizer',
          role: 'Visualization, Analytics & Tuning GUI',
          desc: 'Open-source browser dashboard that visualizes alpha-forge backtest and optimization results — and now runs them. Equity / Drawdown / WFO composite curves, Pearson correlation across multiple strategies, and live-vs-backtest diff, plus GUI-launched backtests / optimization / WFT with a parameter tuning loop (edit → trial run → compare → explicit save). Agents can read results via its REST API. Viewing runs independently of forge.',
          tags: ['Python', 'React', 'SQLite', 'PyPI', 'Apache-2.0'],
          accent: 'var(--accent)',
          links: [
            { label: 'Docs', href: 'docs/alpha-visualizer/' },
            { label: 'GitHub', href: 'https://github.com/alforge-labs/alpha-visualizer', external: true },
            { label: 'PyPI', href: 'https://pypi.org/project/alpha-visualizer/', external: true },
          ],
        },
        {
          id: 'strike',
          badge: 'Dev',
          badgeType: 'dev',
          icon: '⚡',
          name: 'strike',
          role: 'Webhook Execution Server',
          desc: 'Receives external webhook signals via FastAPI and auto-routes API requests to OANDA and moomoo. Records execution and response events as JSONL. Docker-ready for server deployment.',
          tags: ['FastAPI', 'OANDA', 'moomoo', 'Docker', 'Webhook'],
          accent: 'var(--amber)',
          links: [
            { label: 'Setup Guide', href: 'docs/guides/alpha-strike-setup/' },
            { label: 'GitHub', href: 'https://github.com/alforge-labs/alpha-strike', external: true },
            { label: 'PyPI', href: 'https://pypi.org/project/alpha-strike/', external: true },
          ],
        },
      ],
    },
    perf: {
      label: 'Simulation Results',
      title: 'Simulation Results (Live Data)',
      strategy: 'TQQQ · GLD · TLT equal-weight hedged combine (SMA200+ATR trigger) — 5-year simulation',
      period: '2021.05 – 2026.05 (5 years)',
      note: '* Real backtest (incl. 0.05% slippage, price return). A combine of 3× leveraged NASDAQ-100 (TQQQ) hedged via SMA200+ATR, equal-weighted with GLD and TLT. CAGR is just below QQQ buy-and-hold (16.9%) but above SPY (13.7%), with substantially lower max drawdown (-23.3% vs QQQ -35.1%) and higher Sharpe than both benchmarks. Walk-forward tested (WFT) with all 5 out-of-sample windows positive over 2010–2026. Past results do not guarantee future outcomes.',
      stats: [
        { val: '+16.2%', label: 'CAGR',            cls: 'val-pos' },
        { val: '0.91',   label: 'Sharpe Ratio',     cls: 'val-neu' },
        { val: '-23.3%', label: 'Max Drawdown',      cls: 'val-neg' },
        { val: '0.69',   label: 'Calmar Ratio',      cls: 'val-neu' },
        { val: '+113%',  label: 'Total Return',      cls: 'val-pos' },
      ],
      legend: [
        { color: 'var(--accent)', label: 'This Simulation (TQQQ+GLD+TLT hedged)' },
        { color: 'var(--blue)',   label: 'SPY B&H' },
        { color: 'var(--amber)',  label: 'QQQ B&H' },
      ],
      bench: {
        label: 'vs Benchmark (same period)',
        headers: ['', 'SPY B&H', 'QQQ B&H', 'This Simulation'],
        rows: [
          { metric: 'CAGR',    spy: '13.7%', qqq: '16.9%', strat: '16.2%', stratWin: false },
          { metric: 'Sharpe',  spy: '0.84',  qqq: '0.81',  strat: '0.91',  stratWin: true },
          { metric: 'Max DD',  spy: '-24.5%',qqq: '-35.1%', strat: '-23.3%',stratWin: true },
        ],
      },
    },
    roadmap: {
      label: 'Roadmap',
      title: 'Where we\'ve been\nand where we\'re going.',
      items: [
        { period: 'Early March 2026', status: 'done', badgeLabel: 'Done', title: 'Simulation Engine Build', items: ['Simulation engine design & build', 'Data ingestion, investment strategy schema & CLI', 'Optimization pipeline & Pine Script generation'] },
        { period: 'Mid–Late March 2026', status: 'done', badgeLabel: 'Done', title: 'Analysis Feature Expansion', items: ['HMM indicator + walk-forward analysis', 'Backtest history DB & chart generation', 'Risk management (dynamic SL/TP)'] },
        { period: 'Late March 2026', status: 'done', badgeLabel: 'Done', title: 'Live Execution Integration', items: ['alpha-strike Webhook server', 'OANDA & moomoo API execution', 'Execution & response event analysis pipeline'] },
        { period: 'April 2026', status: 'done', badgeLabel: 'Done', title: 'Productization', items: ['License management, binary distribution & CI/CD pipeline', 'Official site launch', 'Claude-driven autonomous parameter search'] },
        { period: 'May 2026', status: 'done', badgeLabel: 'Done', title: 'Beta Release', items: ['alpha-forge v0.4.0 release (macOS / Windows / Linux binaries)', 'alpha-visualizer v0.2.0 published (OSS, TradingView Lightweight Charts)', 'Trial plan launched', 'Documentation polish'] },
        { period: 'Summer 2026', status: 'active', badgeLabel: 'Active', title: 'Public Launch & Commercialization', items: ['Full v1.0 product release', '✅ MCP server published on PyPI — uvx alpha-forge-mcp (Claude Code / Codex / Cursor)', '✅ FRED/ALFRED macro data provider shipped (alpha-forge data alt fetch FRED: / backtest --regime-filter macro:)', 'Support & community setup'] },
      ],
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently Asked\nQuestions',
      items: [
        { q: 'What operating systems are supported?', a: 'macOS (Apple Silicon / Intel), Windows 10 or later, and Linux. AlphaForge ships as a single binary — no Python or runtime install is required. Just download and run.' },
        { q: 'Can I try it for free?', a: 'Yes. The Trial plan requires no Whop signup and never expires. It runs immediately after install, with three limits: historical data through 2023/12/31, up to 50 cumulative optimization runs, and no Pine Script generation. Full functionality unlocks with a Lifetime / Annual / Monthly purchase.' },
        { q: 'Which data sources are supported?', a: 'yfinance (equities / ETFs), moomoo (equities with deeper order book), OANDA (FX / CFD), and Dukascopy (long-horizon FX historical) — four providers in total. All fetched data is cached locally as Parquet on your machine.' },
        { q: 'How does AlphaForge avoid overfitting?', a: 'Optuna TPE Bayesian optimization and Walk-Forward Test (WFT) are standard. Run `alpha-forge optimize run --split` to get in-sample and out-of-sample scores in one command — the gap between them is the primary overfitting signal.' },
        { q: 'Do I need TradingView?', a: 'No, not for strategy authoring, backtesting, optimization, or Pine Script generation — alpha-forge runs standalone. You only need TradingView if you want to deploy the generated Pine Script v6 for alerts/automation on TradingView, or if you wire alpha-strike for automated execution.' },
        { q: 'Can I use it with AI coding agents?', a: 'Yes — that is the core use case. Skills for Claude Code and Codex (5 slash commands like /explore-strategies plus 3 skills) are bundled, and the MCP server (uvx alpha-forge-mcp, alpha) connects Claude Code, Claude Desktop, and Cursor directly. The CLI itself supports --json on every command, a non-interactive mode (FORGE_NONINTERACTIVE=1), and a strict exit-code contract, so overnight autonomous loops run safely unattended.' },
        { q: 'Can I use it on multiple machines? What about updates?', a: 'Both Trial and paid plans cover personal use on multiple devices on an honor-system basis (see the EULA for details). Lifetime always runs on the latest version, with no extra fee for major upgrades like v2.' },
      ],
    },
    systemFlow: {
      label: 'System Flow',
      title: 'Connect research, execution, and live feedback in one loop',
      subtitle: 'AlphaForge builds and optimizes strategies, AlphaStrategies stores deliverables, and AlphaStrike receives TradingView alerts to send orders through Broker APIs. Fills, positions, and P&L return as Live Data — visualized alongside backtest results in AlphaVisualizer for the next analysis cycle.',
      alt: 'AlphaTrade system flow diagram',
    },
    usecases: {
      label: 'Use Cases',
      title: 'A Quant Framework for\nEvery Market and Strategy Style',
      subtitle: 'AlphaForge\'s statistical engine covers the full development, validation, and optimization cycle for quantitative investment strategies — across futures, equities, and FX.',
      items: [
        {
          icon: '🛢️',
          accent: 'var(--amber)',
          label: 'Futures & Commodities',
          title: 'Futures & Commodity Trading',
          desc: 'Apply HMM regime-switching models to commodity futures like crude oil (CL=F) and gold (GC=F). Automatically detect market regime changes and pursue stable returns while limiting drawdown.',
          tags: ['Futures Trading', 'HMM', 'Regime Detection', 'CL=F / GC=F'],
        },
        {
          icon: '📈',
          accent: 'var(--blue)',
          label: 'Equity Index',
          title: 'Equity Index Strategies',
          desc: 'Build multi-indicator strategies combining MACD and RSI on S&P 500 (SPY) and NASDAQ 100 (QQQ). Rigorously validate long-term performance with walk-forward analysis.',
          tags: ['Equity Index', 'MACD / RSI', 'Walk-Forward', 'SPY / QQQ'],
        },
        {
          icon: '💱',
          accent: 'var(--accent)',
          label: 'FX / Forex',
          title: 'Forex Strategies',
          desc: 'Run Bayesian optimization across high-dimensional parameter spaces for major pairs like USDJPY and EURUSD. Find optimal solutions more efficiently than grid search while preventing curve-fitting.',
          tags: ['FX Strategy', 'Bayesian Optimization', 'Currency Pairs', 'USDJPY / EURUSD'],
        },
      ],
    },
    personaUseCases: {
      label: 'Who Is It For?',
      title: 'Start From Your Goal',
      subtitle: 'Choose the entry point that matches your background and goals.',
      personas: [
        {
          icon: '✨',
          label: 'AI Agent Users',
          title: 'AI Agent Users',
          desc: 'Bundled skills + MCP server + non-interactive CLI. Delegate exploration, validation, and Pine Script generation to Claude Code or any other agent in an async workflow.',
          link: '/en/docs/usecases/ai-agents/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '📊',
          label: 'TradingView Users',
          title: 'TradingView Users',
          desc: 'Prototype in Pine Script and bring the real backtesting and optimization to AlphaForge. Export Pine Script back when done.',
          link: '/en/docs/usecases/tradingview/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🐍',
          label: 'Python Developers',
          title: 'Python Developers',
          desc: 'JSON-declarative strategy management, structured CLI output, and Optuna-based optimization — seamlessly integrated with the Python ecosystem.',
          link: '/en/docs/usecases/python-dev/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🔬',
          label: 'Quants & Researchers',
          title: 'Quants & Researchers',
          desc: 'Walk-forward validation, Bayesian optimization, and reproducibility guarantees. A quantitative evaluation environment for researchers who demand statistical rigor.',
          link: '/en/docs/usecases/quants/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '🤖',
          label: 'Automated Trading',
          title: 'Automated Trading',
          desc: 'A complete pipeline: backtest → optimize → generate Pine Script → TradingView alert → Alpha Strike auto-execution.',
          link: '/en/docs/usecases/auto-trading/',
          linkLabel: 'Learn more →',
        },
        {
          icon: '📘',
          label: 'Discretionary → Systematic',
          title: 'Discretionary → Systematic',
          desc: 'Codify the trading rules in your head as declarative JSON, then quantify emotional bias through backtests. Graduate to a reproducible systematic edge.',
          link: '/en/docs/usecases/discretionary/',
          linkLabel: 'Learn more →',
        },
      ],
    },
    longTermValue: {
      label: 'Long-Term Value',
      title: 'Strategies are never finished',
      subtitle: 'Markets, research, and implementation ideas keep changing. alpha-forge is not a one-off backtest tool; it is a development loop for continuously revisiting your strategy assumptions.',
      items: [
        {
          eyebrow: 'Regime Shift',
          title: 'Market regimes change',
          desc: 'A strategy that looks strong once may degrade as volatility, rates, liquidity, and participant behavior shift. Long-lived systems need periodic revalidation instead of one-time confidence.',
        },
        {
          eyebrow: 'Strategy Intake',
          title: 'New ideas keep arriving',
          desc: 'Research platforms such as SSRN and the TradingView Pine Script community continue to surface new methods, indicators, and risk-management ideas. Keeping an intake path open helps turn them into testable candidates.',
        },
        {
          eyebrow: 'Validation Loop',
          title: 'Keep the validation loop moving',
          desc: 'alpha-forge keeps backtesting, Bayesian optimization, walk-forward validation, and Pine Script generation in one flow. New hypotheses can move into reproducible validation without rebuilding the workflow each time.',
        },
      ],
    },
    trustSafety: {
      label: 'Trust, Safety, and Limits',
      title: 'What to know before you buy or use AlphaForge',
      subtitle: 'AlphaForge is a developer tool built around local execution. Review how data is handled, what license activation sends, what the investment-risk limits are, and how plan limits work.',
      docsHref: '/en/docs/legal/trust-safety-limits/',
      docsLabel: 'Read the Trust, Safety, and Limits guide',
      items: [
        {
          eyebrow: 'Local First',
          title: 'Strategy data stays local',
          desc: 'Backtest settings, API keys, trade history, and strategy data normally remain in your local environment and are not sent to Alforge Labs servers.',
        },
        {
          eyebrow: 'License',
          title: 'Activation sends only required license data',
          desc: 'During license activation, only information required for verification, such as the license key, instance name, and activation timestamp, is sent to the external license service.',
        },
        {
          eyebrow: 'Risk',
          title: 'This is not financial advice',
          desc: 'AlphaForge is research and validation software. Backtests and simulation results do not guarantee future outcomes, and every trading decision remains your responsibility.',
        },
        {
          eyebrow: 'Plans',
          title: 'Trial / Monthly / Annual / Lifetime',
          desc: 'The Trial plan (no Whop registration, free) has data-date and optimization trial limits. Pick any of Lifetime (one-time), Annual, or Monthly to unlock the latest data, unlimited trials, and Pine Script export.',
        },
      ],
    },
    follow: {
      label: 'Updates',
      title: 'Follow the build\nin real time.',
      desc: 'Simulation results, feature updates, and behind-the-scenes development shared regularly.',
      cta: 'Follow on X',
    },
    disclaimer: {
      title: '⚠️ Important Disclaimer (Please Read)',
      items: [
        { label: 'Software Provision', text: 'This product is a developer software tool for time-series data simulation and pipeline automation. It does not recommend any specific operational approach.' },
        { label: 'About Simulation Results', text: 'Simulation results are based on historical data and do not guarantee future outcomes.' },
        { label: 'User Responsibility', text: 'All outcomes, including those from automated API execution, parameter settings, and system errors, are the sole responsibility of the user.' },
      ],
    },
    footer: {
      copy: '© 2026 Alforge Labs.',
      note: 'This site provides developer software tools. Nothing here constitutes professional advice or specific product recommendations.',
      links: [
        { label: 'Terms', url: '/terms.html' },
        { label: 'Privacy', url: '/privacy.html' },
      ],
    },
  },
};
